routes/web.php
<?php

use App\Http\Controllers\MagazineController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    abort(404);
});

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['middleware' => ['auth']], function () {
    Route::resource('magazines', MagazineController::class)->except('show');
});
Route::get('/insider/{magazine}', [MagazineController::class, 'show'])->name('magazines.show');

app/Models/Magazine.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Magazine extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'external_id',
        'preview',
    ];

    public const PAGINATE = 10;

    public static function paginate(?string $name = null) {
        return self::query()
            ->when(!is_null($name), function ($query) use ($name) {
                $query->where('name', 'LIKE', "%$name%");
            })
            ->orderByDesc('id')
            ->paginate(self::PAGINATE);
    }

}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MagazineController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Magazine\StoreRequest;
use App\Http\Requests\Magazine\UpdateRequest;
use App\Models\Magazine;
use App\Services\MagazineService;
use Illuminate\Http\Request;

class MagazineController extends Controller
{

    public function index()
    {
        $magazines = Magazine::paginate(
            \request()->query('name')
        );
        return view('magazines.index', compact('magazines'));
    }

    public function create()
    {
        return view('magazines.create');
    }

    public function store(StoreRequest $request, MagazineService $service)
    {
        $payload = $request->validated();
        $payload['preview'] = $service->handleUploadedPreview($request->file('preview'));
        Magazine::create($payload);
        return to_route('magazines.index');
    }

    public function edit(Magazine $magazine)
    {
        return view('magazines.edit', compact('magazine'));
    }

    public function update(UpdateRequest $request, Magazine $magazine, MagazineService $service)
    {
        $payload = $request->validated();
        if (isset($payload['preview'])) {
            $payload['preview'] = $service->handleUploadedPreview($request->file('preview'));
        }
        $magazine->update($payload);
        return to_route('magazines.index');
    }

    public function destroy(Magazine $magazine)
    {
        $magazine->delete();
        return back();
    }

    public function show(Magazine $magazine) {
        return view('magazines.show', compact('magazine'));
    }

}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        @auth
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('magazines.index') }}">
                                {{ __('Magazines') }}
                            </a>
                        </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/magazines/create.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Create Magazine</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("home") }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route("magazines.index") }}">Magazines</a></li>
                        <li class="breadcrumb-item active">Create Magazine</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container">
            <form role="form" enctype="multipart/form-data" method="post" action="{{ route('magazines.store', \request()->query()) }}">
                <div class="row">
                    <div class="col-xl-6 col-sm-12">
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name"
                                   class="form-control @error('name') is-invalid @enderror"
                                   id="name"
                                   value="{{ old('name') }}"
                                   placeholder="Name">
                        </div>

                        <div class="form-group">
                            <label for="preview">Preview</label>
                            <input class="form-control @error('preview') is-invalid @enderror" type="file" accept=".jpg, .jpeg, .png" name="preview" id="preview">
                        </div>

                        <div class="form-group">
                            <label for="external_id">External Id</label>
                            <input id="external_id" name="external_id"
                                   class="form-control @error('external_id') is-invalid @enderror" value="{{ old('external_id') }}" type="text">
                        </div>

                    </div>

                    <div class="mt-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
                <!-- /.row -->
            </form>
        </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/magazines/edit.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Edit Magazine</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route("home") }}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{{ route("magazines.index") }}">Magazines</a></li>
                        <li class="breadcrumb-item active">Edit Magazine</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container">
            <form role="form" enctype="multipart/form-data" method="post" action="{{ route('magazines.update', ['magazine' => $magazine->id]) }}">
                <div class="row">
                    <div class="col-xl-6 col-sm-12">
                        @method('PUT')
                        @csrf
                        <div class="form-group">
                            <label for="name">Name</label>
                            <input type="text" name="name"
                                   class="form-control @error('name') is-invalid @enderror"
                                   id="name"
                                   value="{{ old('name', $magazine->name) }}"
                                   placeholder="Name">
                        </div>

                        <div class="form-group">
                            <label for="preview">Preview</label>
                            <input class="form-control @error('preview') is-invalid @enderror" type="file" accept=".jpg, .jpeg, .png" name="preview" id="preview">
                        </div>

                        <div class="form-group">
                            <label for="external_id">External Id</label>
                            <input id="external_id" name="external_id"
                                   class="form-control @error('external_id') is-invalid @enderror" value="{{ old('external_id', $magazine->external_id) }}" type="text">
                        </div>

                    </div>

                    <div class="mt-4">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>

                </div>
                <!-- /.row -->
            </form>
        </div><!-- /.container-fluid -->
    </section>
@endsection

resources/views/magazines/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form class="row g-3 mt-2">
                <div class="col-6 col-md-3">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" value="{{ \request()->get('name') }}" name="name" id="name">
                </div>
                <div class="col-auto">
                    <label for="" style="visibility: hidden; display: block;">Hidden</label>
                    <button type="submit" class="btn btn-primary mb-3">Submit</button>
                </div>
                <div class="col-auto">
                    <label for="" style="visibility: hidden; display: block;">Hidden</label>
                    <a href="{{ route('magazines.create', \request()->query()) }}" class="btn btn-success mb-3">Create
                        Magazine</a>
                </div>
            </form>


            @if($magazines->isNotEmpty())
                <div class="table-wrapper">
                    <table class="table">
                        <thead class="table-dark">
                        <tr>
                            <th scope="col">Preview</th>
                            <th scope="col">Name</th>
                            <th scope="col">External Id</th>
                            <th scope="col">URL</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($magazines as $magazine)
                            <tr>
                                <td>
                                    @if($magazine->preview)
                                        <img src="/storage/{{ $magazine->preview }}" style="height: 50px" alt="Preview">
                                    @else
                                        No Preview
                                    @endif
                                </td>
                                <td>{{ $magazine->name }}</td>
                                <td>{{ $magazine->external_id }}</td>
                                <td>
                                    <a href="{{ route('magazines.show', ['magazine' => $magazine->id]) }}">{{ route('magazines.show', ['magazine' => $magazine->id]) }}</a>
                                </td>
                                <td>
                                    <div class="d-flex gap-2">
                                        <a class="p-0" class="m-4"
                                           href="{{ route('magazines.edit', ['magazine' => $magazine->id]) }}">
                                            <button class="btn btn-primary">
                                                @svg('bi-pencil')
                                            </button>
                                        </a>
                                        <form method="post"
                                              action="{{ route('magazines.destroy', ['magazine' => $magazine->id]) }}">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-danger">@svg('bi-trash')</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                {{ $magazines->links("pagination::bootstrap-5") }}
            @else
                No magazines yet...
            @endif

        </div>
    </div>
@endsection

resources/views/magazines/show.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{{ $magazine->name }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">
    <script>
        document.addEventListener('DOMContentLoaded', function(){ // Аналог $(document).ready(function(){
            let css = '.fullscreen-button,.fullscreen-button-mini{display:none!important}'
            let style = document.createElement('style');
            style.type = 'text/css';
            if (style.styleSheet){
                style.styleSheet.cssText = css;
            } else {
                style.appendChild(document.createTextNode(css));
            }
            let frame = document.getElementById('magazine')
            frame.contentWindow.document.head.appendChild(style);
        });
    </script>
</head>
<body>
<div class="position-absolute">
    <iframe id="magazine" name="magazine" type="text/html" scrolling="no" frameborder="0" allowfullscreen="allowfullscreen"
            allow="accelerometer; autoplay; encrypted-media; fullscreen *; gyroscope; picture-in-picture;"
            src="https://online.flippingbook.com/view/{{ $magazine->external_id }}"
            style="width: 100%; height: 100vh;">
    </iframe>
</div>
</body>
</html>